### ISSUE TITLE
Add "change email address" option to editAccount page

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/userdetails#1]
To be deployed only after BVP has been fixed to use userIds instead of username (email address) and foreign key. Check https://github.com/AtlasOfLivingAustralia/volunteer-portal/issues/37 is closed before proceeding.

http://auth.ala.org.au/userdetails/registration/editAccount

Re-activate the edit email address and change code so that **both** `username` and `email` are changed (current code only changes `email` column).

**Comment by nickdos** [comment]
I think this is done - just test it and close if satisfied/.

**Comment by javier-molina** [comment]
Already in master as part of commit  [Sync userName with email when email is updated](https://github.com/AtlasOfLivingAustralia/userdetails/commit/664b2e3e272b58ad617a826bcd49d058256cc9f4) 

Code updates both e-mail and username fields in the DB
