### ISSUE TITLE
userdetails-config.properties not in sync with Config.groovy

### ISSUE THREAD

**Issue by mbohun** [AtlasOfLivingAustralia/userdetails#10]
https://github.com/AtlasOfLivingAustralia/userdetails/blob/master/grails-app/conf/Config.groovy `security.cas.loginUrl` property does not exist in the `/data/userdetails/config/userdetails-config.properties` (as in the hardcoded 'default' val from `Config.groovy` will be always used)

other properties and other projects' `Config.groovy` files need to be checked for this problem too.

**Comment by m-r-c** [comment]
I have updated the properties file in the ala-install repo (https://github.com/AtlasOfLivingAustralia/ala-install/blob/master/ansible/roles/userdetails/templates/userdetails-config.properties) with all required properties, and have removed them from the Config.groovy file.
