### ISSUE TITLE
Verify assertions_sync.py script and make sure it gets the correct refresh token

### ISSUE THREAD

**Issue by sat01a** [AtlasOfLivingAustralia/userdetails#146]
I’ve got a problem where our new assertions script that Mahmoud wrote before we went on leave isn’t working, so no user assertions are appearing on the ALA. Mahmoud’s script passes a clientid and secret:

+ python3 ./assertions_sync.py --file ./jwt-auth.json --clientId xxxx --clientSecret yyyy --tokenUrl https://auth.ala.org.au/cas/oidc/oidcAccessToken https://biocache.ala.org.au/ws/sync
Token expired. Refreshing token...

and we get this error:
Unable to refresh access token.  400
Error encountered during request  401

Reported by: @peggynewman

**Comment by joe-lipson** [comment]
Updated the refresh token and tested that the script could fetch a new access token, verified with Peggy that it's working again. Thanks all for the help on this one
