### ISSUE TITLE
Get and Set user property invocation issues. 

### ISSUE THREAD

**Issue by sughics** [AtlasOfLivingAustralia/userdetails#169]
ALA apps make calls to the userdetails app APIs to get `/property/getProperty` and save `/property/saveProperty` user properties e.g. bicoache-hubs makes calls to save and get a user's data quality preferences e.g. POST AND GET on `https://biocache.ala.org.au/user/dqProfile`  which internally attempts to invoke the save and get properties endpoint. 

It appears that these endpoints have a ROLE requirement of `ROLE_ADMIN` for invocation. When invoked by other ALA apps, the JWTs sent by these apps is of type `client_credentials` (which do not include any  or role information) and as such the invocation is unsuccessful resulting in an error. 

`/property/saveProperty`  also requires `users/write`  scope, currently missing from biocache-hub configs. This can be added to to config but  we will still need to ensure that the above role  requirement issue with  `/saveProperty`  and `/getProperty` endpoints  is resolved before either of the APIs can be invoked successfully.

We might need another way/endpoint of saving and getting user properties?

- [x] TODO - investigate potential solutions.

cc-@yasima-csiro

**Comment by yasima-csiro** [comment]
Solution - override requiredRole to non on the @PreAuthorise annotation. 

it was just an authorised system / ip allow list check before OIDC, so role check is not required now.

**Comment by sughics** [comment]
This fix works for getting and setting user properties via the userdetails api. 

For cognito backed userdetails however, there is a limit on AWS Cognito itslef  on the maximum length allowed for a user property key(20)  which prevents certain user attributes from being saved. e.g. This prevents user preference for UI expansion state of data quality filter on biocache hubs being saved.
