### ISSUE TITLE
Update Facebook Graph API version

### ISSUE THREAD

**Issue by kylie-m** [AtlasOfLivingAustralia/userdetails#171]
The Facebook graph API that is associated with our CAS Facebook login app is being deprecated on September 14th this year. We need to update it, the latest is v17. The FB upgrade tool says we shouldn't be affected by the change. We just need to verify that and do it before September 14th.

FB notification:

v11.0 upgrade reminder
 
 
Your App, Atlas of Living Australia Login, currently has access to Graph API v11.0 which will reach the end of its 2-year lifetime on 14 September, 2023. To ensure a smooth transition, please migrate all calls to Graph API v12.0 or higher. Use the [API Upgrade Tool ](https://www.facebook.com/n/?l.php&u=https%3A%2F%2Fdevelopers.facebook.com%2Ftools%2Fapi_versioning%2F387243798138138%2F&h=AT2UjZbyxMjPsk_ZpSsb4HP_nQoxfLuPO_K24ZTvZwKSo5bYVeA8Slt262uw5hhcmN5N1bMbk9g7eFs8ZGqD0vCBiFT6oONFKgUHshqgoo5GcwzGWK-sFHl6yeckodg2A2nwzQ&aref=1692038807239232&medium=email&mid=602e63277376eG5afc86c6799cG602e67c0d3a40G191&n_m=fbapp%40ala.org.au)to understand exactly how this change will impact your app.
 
Note: If you do not see any impacted calls in the API Upgrade Tool, your app/code may not be affected by this upgrade.
 
Visit our [changelog ](https://www.facebook.com/n/?l.php&u=https%3A%2F%2Fdevelopers.facebook.com%2Fdocs%2Fapps%2Fchangelog%2F&h=AT2tkkN7Ln63NV8Uz6YZnOeq7iqWhh2Y0ErGh9Y-QfSkpK9sb-2t3myqZlYcDSeZmygJQw2IS4mcTpsNmbQWz-obY88Sj7ceM2Co5jS839HdMUHrZ-6439iO71zfW7Y6fLNekQ&aref=1692038807239232&medium=email&mid=602e63277376eG5afc86c6799cG602e67c0d3a40G191&n_m=fbapp%40ala.org.au)to see the full list of changes in all Graph API versions.
 
You can view this and other developer notifications related to your app in the app dashboard.
 
   
   
 
[Visit app dashboard](https://developers.facebook.com/apps/387243798138138/alerts/?ref=email&alert_id=279686484685810)

**Comment by joe-lipson** [comment]
This is done, we're on v17 now in production and test
