### ISSUE TITLE
Flickr linking broken

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/userdetails#18]
https://auth.ala.org.au/userdetails/myprofile

Click the link: "Link to my Flickr account"

returns error page with:

>URI: /userdetails/oauth/flickr/authenticate
Class: org.scribe.exceptions.OAuthException
Message: Response body is incorrect. Can't extract token and secret from this: 'oauth_problem=consumer_key_unknown'

Not sure this feature is worth keeping so I suggest we comment it out or just delete completely.

**Comment by mbohun** [comment]
the flickr OAuth key, secret, and (userdetails) callback have to be set in order for the linking of flickr account to work, example:
```properties
oauth.providers.flickr.key=[REMOVED]                                                                                                       
oauth.providers.flickr.secret=[REMOVED]                                                                                                                    
oauth.providers.flickr.callback=https://nci-cas4.ala.org.au/userdetails/profile/flickrCallback
```
