### ISSUE TITLE
Add "disable account" button to editAccount page

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/userdetails#2]
This is effectively a "delete account" button but the functionality should simply disable the account. Maybe set the `locked` column to `1`?

Needs a warning confirmation saying the account will be deleted. 

We also need to think about what happens if the user wants to re-activate their account. If they try to create a new account it will probably fail, so maybe catch this scenario and generate an warning?

**Comment by javier-molina** [comment]
CAS don't seem to read `locked` flag at all when authenticating. I will go set `active` to  `0` instead

**Comment by javier-molina** [comment]
https://upsource.ala.org.au/ala-install/review/AI-CR-3

https://upsource.ala.org.au/userdetails/review/USERDETAILS-CR-1

**Comment by m-r-c** [comment]
Is there anything else that needs to be done when disabling a user? What about disabling any alerts they might have?

**Comment by nickdos** [comment]
Yes I think we should remove all alerts for the user too - it won't be automatic. Might require a new service on alerts along the lines of `removeAllAlertsForUserId()`.

**Comment by m-r-c** [comment]
I have created a new task in the Alerts repo to create the new service rather than blowing out the scope of this task: https://github.com/AtlasOfLivingAustralia/alerts/issues/16.

**Comment by javier-molina** [comment]
Thanks for creating a separate ticket, giving my limited knowledge of these system I was not aware dependencies such as alerts.

Will ticket AtlasOfLivingAustralia/alerts#16 be added to the current sprint?

**Comment by m-r-c** [comment]
Yep. I think we have the time for it, and we had another task for Alerts, too.
