### ISSUE TITLE
Log4j config need fixing

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/userdetails#20]
Prod log has lots of DEBUG level logging from `ala-bootsptrap2` but no ERROR or WARN level output. 

Check conf file for latest log4j config template and then test with `grails prod run-app`.

**Comment by javier-molina** [comment]
https://upsource.ala.org.au/userdetails/review/USERDETAILS-CR-4 

Enabled warning logging as it could convey relevant information.

/var/log/tomcat7/userdetails.log file does not exist in production but there are backups that show it did.

running userdetails from vagrant creates the log file without issues. Most likely userdetails@prod only need a bounce to make the log work again with the current config, if not in a hurry, that can be done once the new version of userdetails is released.

On the other hand [Logback Plugin](https://grails.org/plugin/logback) was of no use as it messed with the standard grails (shell) output.

On the positive side, I was not that far as grails 3.x replaced log4j by logback using native logback groovy configuration.
