### ISSUE TITLE
Login screen - change username to email

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/userdetails#24]
We've had a few users get confused when logging in for the first time, as they interpret the "user name" field to be the name they entered when registering. 

The login form expects their email address, so I think we should explicitly say this.

![image](https://cloud.githubusercontent.com/assets/532845/10297063/1172f26c-6c1a-11e5-8d5a-dfa10f32c321.png)

**Comment by javier-molina** [comment]
This is a CAS screen and was already fixed in commit  [2357323](https://github.com/AtlasOfLivingAustralia/ala-cas-2.0/commit/2357323311db9901d39c008aeb0bf08f93eb42fa)
