### ISSUE TITLE
Admin screen - add export all users to CSV

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/userdetails#27]
Requested by Lee but useful for bulk email list generation.

Add some options (params)
- include inactive users (default to false)
- include extra data fields (e.g. organisation, primaryUserType, etc. - default to false)
- restrict to users with a given (or list of) ROLE

Should respect the IP address whitelist (that other POST services are checking against). So it needs to provide meaningful error if users attempts to hit this endpoint and their IP address is not accepted.

**Comment by Tasilee** [comment]
As long as all the fields are listed in the CSV, it is very easy to sort/filter etc in Excel. So any filtering etc is not a priority.

At some point, after any easy tidy-ups of the variables, it may well be worth emailing users to update their profile info. This would in itself identify bung/old emails etc.

**Comment by javier-molina** [comment]
Do we want to expose all fields in users table or exclude some such as id? 

How about extra fields? These are the different properties in profiles:

city
organisation
primaryUserType
secondaryUserType
state
telephone
flickrId
flickrUsername
newsletterSubscription
bulkCreatedOn

Finally is not specified but how about adding user roles, is this something that needs to be included as well?

**Comment by Tasilee** [comment]
As this is an admin tool that is extremely useful to understanding our communities and usage, ALL the available fields should be exported (viz.)-

----------User controlled fields
firstname
lastname
email
organisation
city
state 
telephone
primary usage (semi-controlled list)
secondary usage (semi-controlled list)
--------linked user controlled
flickrid
flickrUsername
--------alerts (mainly off/on)
alert frequency (hourly, daily, weekly monthly)
new records
(new) spatial layers
new occurrence datasets
(new) annotations
(new) citizen science records
(new) blogs and news
(new) species lists
new images
(new) citizen science records with images
-----------custom alerts

In the case of custom alerts, it would be handy to know just how many have been created. 

Example of how this information is used (that is a manual process currently)-

1. Understanding the ALA communities
2. Understanding user background in checking generality of species lists (e.g., authoritative lists).
3. Context for addressing user issues
4. Tuning functionality to community-type needs
5. Reporting usage. We currently only report download categories on dashboard.ala.org.au so there is a STONG case for better summary reporting of usage by user types.
6. Profiling usage types of SP tools and services (via http://spatial.ala.org.au/actions/dashboard - admin tool)
 etc

**Comment by javier-molina** [comment]
Looks like alerts needs to be sourced from another system and can  blow the
original estimate for this task. I will create a task to follow up on that.

Finally I'm planning to include roles in the output too. Any objections.

**Comment by nickdos** [comment]
Yes - alerts are out of scope for this issue. Very little benefit for a big outlay of work.

**Comment by javier-molina** [comment]
https://upsource.ala.org.au/userdetails/review/USERDETAILS-CR-3

**Comment by nickdos** [comment]
Hi @javier-molina, could you update this issue when these changes are deployed to production, so @Tasilee can give it a test? Thanks.
