### ISSUE TITLE
Investigate whether more work is required on the user preferences feature

### ISSUE THREAD

**Issue by m-r-c** [AtlasOfLivingAustralia/userdetails#28]

**Comment by javier-molina** [comment]
Investigate with Temi if work here is finished and whether biocache is using now preferences from this system rather than its own.

**Comment by javier-molina** [comment]
Temi confirms that the functionality to consume and update user preferences (properties) has already been completed in userdetails.  See pull request for details. 
https://github.com/AtlasOfLivingAustralia/userdetails/pull/23 


These features are already used by biocache:  https://github.com/AtlasOfLivingAustralia/biocache-hubs/commit/e4e55b4ca6d106a169c0ef83c89138982eab11f8
