### ISSUE TITLE
Password reset allows double submit and produces a confusing error when it does

### ISSUE THREAD

**Issue by chrisala** [AtlasOfLivingAustralia/userdetails#33]
Users are successful in resetting password, on first submit and if they accidentally click the button twice a second attempt fails and produces an error message resulting in the user thinking they can't log in when they can.

**Comment by pwscsiro** [comment]
N.B. I am unable to replicate the issue locally.

**Comment by pwscsiro** [comment]
Went for the simplest option, as the workflow for this form is -> submit form, run validation, show any errors OR submit form, send email, display success page, i.e. we go onto new page if successful. Tested and existing validation still works and only 1 email is ever sent (previously I was getting one email per click, but couldn't generate error).
