### ISSUE TITLE
Add link to "terms of use" to registration page

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/userdetails#51]
The new login page has a link to the ALA terms of use but the registration page only mentions the ALA privacy policy. Can the terms of use also be added to that page please?

https://auth.ala.org.au/userdetails/registration/createAccount

**Comment by javier-molina** [comment]
@sbearcsiro sorry to be a pain but could the Account in "Your Account" heading be changed to lower case to be consistent with the other headings and also the "Create your account heading on the left?

Other than that the actual Terms of use are there as expected.

> Do I need to create an account?
> If you already have an account with an institution that participates in the Australian Access Federation or an account with Google, Facebook or Twitter we highly recommend login using it instead as that will:

> Save you typing the basic information like your name and email address that you already have with one of those accounts.
You don't have to set and remember yet another password.
Your account will be activated without going through verification emails
Overall you will save time
Of course if you don't have an account with such providers or prefer to use a different email you still can create an account with us by filling in the information on the left.

> Your Account
Your email address will be your ALA account login.

> An "account activation" link will be emailed to the address provided. You need click this link, in order to complete the registration process. Note, you may need to check you spam/junk mail folder, as activation emails sometimes get caught by mail filters.

> Privacy policy
> For the Atlas' policy on the collection and use of personal information see our Privacy Policy.

> Terms of use
> For the Atlas' terms of use see our Terms of Use
