### ISSUE TITLE
Allow HTML in bulk user template

### ISSUE THREAD

**Issue by chrisala** [AtlasOfLivingAustralia/userdetails#52]
I think when we moved to a version of grails that escapes HTML by default, this was disabled.
It is only usable by ALA Admins so should be safe to do.

**Comment by javier-molina** [comment]
The class au.org.ala.userdetails.AdminController uses PreAuthorise  to force code to be used only by admins including the call to userService.bulkRegisterUsersFromFile that eventually will populate the emailBody 'unescaped' by https://github.com/AtlasOfLivingAustralia/userdetails/commit/6180f4c85e4640e5a6b5e7201d27745fcfadfc20 

It would be nice to escape any JavaScript content and let html as some additional protection but looks like grails does not offer something like that out of the box. 

The change indeed seems to restore the original behaviour of the reset password functionality.
