### ISSUE TITLE
Report from a user with a message about account locked when attempting to re-register

### ISSUE THREAD

**Issue by ansell** [AtlasOfLivingAustralia/userdetails#60]
A user sent a message to the support email when they received a message about their account being locked after they attempted to re-register their account.

```
I registered for ALA and have not been able to gain access.

I assumed that my registration had not worked and tried to register again but there is this message - "A user is already registered with the email address [REDACTED]@[REDACTED] however it is currently disabled.”

Could you please enable my account.
```

Their account was activated and not locked according to the admin interface. Sending the user to the reset password page could be more useful than suggesting the account was locked in this case.

Refs ticket 27616 in helpdesk

**Comment by timhicks-ala** [comment]
Userdetails does not appear to differentiate between disabled or unactivated when attempting to log in - a user attempting to log in with an account that is neither disabled nor activated will be shown a message saying the account is disabled. See ticket 44247 for an example of this. It's possible that user found their activation email and activated the account themselves before the response was sent.

**Comment by Rita-C** [comment]
Requirement is a subset of #88
