### ISSUE TITLE
Improve activation/reset email

### ISSUE THREAD

**Issue by javier-molina** [AtlasOfLivingAustralia/userdetails#67]
There are a few improvements on the actual email generated to users on activation/password reset and server configuration that will increase the likelihood of emails not been treated as spam.

- Avoid generic emails. emails should be addressed to the recipient and include contact details.
- If not done already, add [SPF](https://support.google.com/a/answer/33786?hl=en) to emails 
- If not done already, add [DKIM](https://support.google.com/a/answer/174124?hl=en) to emails 

Also note from Peter A.:

> We also had a comment from someone that the email was rejected because the reverse DNS of the sending server didn’t resolve. We would need to specifically ask Amazon to setup a custom reverse DNS for the auth servers to resolve that case.

**Comment by matthewandrews** [comment]
This is a very old issue!  Re the second and third points, SPF has been in place for a long time.  We don't use Amazon for mail any more; we use Google Apps. Outgoing mail sent via Google Apps has DKIM.
