### ISSUE TITLE
Web site redesign testing

### ISSUE THREAD

**Issue by javier-molina** [AtlasOfLivingAustralia/userdetails#71]
1.  Help > Contact us and Contact us links in header point to invalid url https://auth-test.ala.org.au/contact-us/

2. Unable to create account 
https://auth-test.ala.org.au/userdetails/registration/createAccount

After filling in fields and clicking Create account I get

```
ERR_TOO_MANY_REDIRECTS
```

![Screen Shot 2019-07-16 at 11 43 29 am](https://user-images.githubusercontent.com/8326394/61259821-3c134a00-a7bf-11e9-8389-ce765c3bd1ca.png)

**Comment by sbearcsiro** [comment]
Issues are resolved
