### ISSUE TITLE
Update iNaturalist biocache query to use alau_user_id field

### ISSUE THREAD

**Issue by peggynewman** [AtlasOfLivingAustralia/userdetails#78]
Update the biocache queries on the user profile page related to inaturalist such that they look for the user id in the alau_user_id field.

Example links below:

View iNaturalist observations:
`https://biocache.ala.org.au/occurrences/search?q=data_resource_uid:dr1411&fq=alau_user_id:<inatLogin>
 `
View iNaturalist and Sightings:
`https://biocache.ala.org.au/occurrences/search?q=data_resource_uid:dr1411%20OR%20data_resource_uid:dr364&fq=alau_user_id:<inatLogin>%20OR%20alau_user_id:%<alaUserId>%22`

**Comment by nickdos** [comment]
So the text:

> View your timeline of sightings recorded through the Atlas

should be changed to 

> View iNaturalist observations 
and 
> View iNaturalist and Sightings

as separate dot points?

Because there is a delay in between submitting a sighting (in iNat) and it appearing in the Biocahce, we might want to link back to the user's account in iNatalist (which will be up-to-date). We've previously had support tickets about this, as users assume the 2 systems are linked (in real-time).

**Comment by peggynewman** [comment]
We agreed to leave this one because users don't like change, and now I think it's actually worded quite well:

- View your timeline of sightings recorded through the Atlas

I wonder if we should just add these links to the top (if the accounts are linked):

- View your iNaturalist observations in the ALA
- View your iNaturalist and ALA observations in the ALA
- Go to iNaturalist Australia
 
I want to keep the links in the grey box because it gives a visual indication of why linking your accounts was a useful thing to do. Although perhaps we can change it to say:

_You can now use the above links to find your iNaturalist observations in the ALA. Records are harvested from iNaturalist weekly._

**Comment by peggynewman** [comment]
Duplicate of #77
