### ISSUE TITLE
Registration form bug

### ISSUE THREAD

**Issue by djtfmartin** [AtlasOfLivingAustralia/userdetails#8]
Reported by Alison Vaughan.

I've noticed a bug in the registration forms a couple of times recently when encouraging other people to register. If you make any errors (such as the password being too short, or missing a required field), the 'Create account' button stays inactive even after the mistakes have been corrected. The only way to get the button active again is to refresh the page and start filling out the form again. This happens in Firefox, but I've just tested it in Chrome and it works okay.

**Comment by sbearcsiro** [comment]
Tested locally and this issue appears to be fixed now.  Possibly due to the new skin.
